server:
  port: 9011
spring:
  application:
    name: tensquare-manager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tensquare_base:
      path: /base/**
      serviceId: tensquare-base
    tensquare_user:
      path: /user/**
      serviceId: tensquare-user
    tensquare_qa:
      path: /qa/**
      serviceId: tensquare-qa
jwt:
  config:
    key: itcast